### ISSUE TITLE
Unable to use multiple aggregate fields

### ISSUE THREAD

**Issue by jhljonm** [burke-software/django-report-builder#120] opened 2014-08-06 16:01 UTC
When adding multiple aggregate 'Count' columns on foreign key fields to a report, both columns display the same value - even though they're based on different models.

**Comment by bufke** [comment] 2015-01-27 04:25
Group by and aggregate are broken - duplicate of https://github.com/burke-software/django-report-builder/issues/20

**Closed by bufke** 2015-01-27 04:25 UTC
