### ISSUE TITLE
Problem with selected field

### ISSUE THREAD

**Issue by lspitaels** [burke-software/django-report-builder#130] opened 2015-02-04 09:52 UTC
Good morning,

I have a problem with some selected field. Instead of showing the type of the field, it's showing 'Invalid'. I don't know what to do. So if you can help me, it should be great.

![report-builder](https://cloud.githubusercontent.com/assets/7034710/6038255/bb826c76-ac5b-11e4-9fe0-121fa6e34927.png)

Thanks,
Laurent

**Comment by bufke** [comment] 2015-02-04 23:23
This is a new feature to attempt to note bad fields. For example if you save a report with a reference to fname and changed the database to first_name the report will break. Previously it would 500 with no helpful message.

What is the chain of fields that causes this? For example Root model > ManytoMany > Charfield

**Comment by lspitaels** [comment] 2015-02-05 07:33
Thank you for your answer.
The chain of fields causing this problem is Root model > ManytoOne > Charfield (and other field too).
I tried to change the root model but I have the same issue and I didn't change the name of my fields inside the database.

Cheers,
Laurent

**Comment by bufke** [comment] 2015-02-06 17:36
Thanks  - I added this to my demo models. https://github.com/burke-software/django-report-builder/commit/5dc6781b1d8263b46ea6a1823e1a83358dfb11a5

So for now I can't reproduce. Do you see anything differences from my demo?

![screenshot from 2015-02-06 12 30 32](https://cloud.githubusercontent.com/assets/739307/6084090/109e5a2a-adfc-11e4-8cab-f4bc80ad4121.png)

I tested from git master - which I believe only has UI changes from the pypi release. Make sure report-utils is up to date as defined in the report builder setup.py dependencies.

**Comment by i-maginary** [comment] 2015-02-07 11:51
Hi, I have the same problem. My chain is Root model > ForeignKey > Charfield.
Though it is not very consistent. One CharField from the same ForeignKey chain becomes Invalid while another does not:
![djangoreportbuilder](https://cloud.githubusercontent.com/assets/8666131/6091977/2f8abf72-aecf-11e4-9220-b252cd69c39c.png)

Though when opening developer tools, I see a lot of get requests like these:
    "GET /report_builder/%7B%7B%20static(%27report_builder/img/add.svg%27)%20%7D%7D HTTP/1.1" 200 2537"
Looks like unresolved angular/django template variables.
I also noticed several "BrokenPipeError: [Errno 32] Broken pipe" errors every time I click on "Display".

Not sure if these are related to the Invalid field type issues.

I am using Django 1.7.4 with latest django-report-builder from PyPI. I am busy running "fig up" to test your demo project and will report back.

**Comment by v-bornov** [comment] 2015-02-09 10:01
I have the same problem.
My chain is Root model > ForeignKey > Charfield.

Probably problem in all model relations.

**Comment by bufke** [comment] 2015-02-09 15:10
Thanks for investigating everyone - if someone can come up with an exact sample and add it to demo models that would be ideal.

The strange GET request is normal. It's running an angular function to append the correct static url. As I can see the images and it says 200 it's working it's just really odd looking in dev tools.

**Comment by orlovegor** [comment] 2015-02-10 08:53
I've been having the same problem today.
Very simple setup: select user_id, group_id and group_name for django Users:
![2015-02-10 11-49-21 127 0 0 1 8001 report_builder report 4](https://cloud.githubusercontent.com/assets/4242339/6124075/1f859536-b11b-11e4-91f3-acf5acf50e2b.png)

Which gives me results without group name in preview and export:
![2015-02-10 11-49-46 127 0 0 1 8001 report_builder report 4](https://cloud.githubusercontent.com/assets/4242339/6124082/34fab7c0-b11b-11e4-8724-a457dd2faf4d.png)

And after refreshing the page group_name is marked as invalid:
![2015-02-10 11-50-19 127 0 0 1 8001 report_builder report 4](https://cloud.githubusercontent.com/assets/4242339/6124087/448a29fa-b11b-11e4-8113-9edef99c7d34.png)

**Comment by bufke** [comment] 2015-02-10 18:48
I've reproduced it using the django auth models as described thanks @orlovegor

**Comment by bufke** [comment] 2015-02-10 19:02
Check out the fix, wouldn't mind testing before I push to pypi.

**Closed** 2015-02-10 19:03 UTC

**Comment by v-bornov** [comment] 2015-02-11 03:23
I have all the works.
Thank you!

**Comment by v-bornov** [comment] 2015-02-11 03:58
In reports generated using celery the same problem with related fields.

**Comment by orlovegor** [comment] 2015-02-11 11:20
Now it seems that expanding dropdown when I press on plus sign doesn't work anymore so no User attributes are selectable.
![2015-02-11 14-15-45 127 0 0 1 8001 report_builder report 6](https://cloud.githubusercontent.com/assets/4242339/6146003/05e9d018-b1f9-11e4-91b8-4f0620a19406.png)

**Comment by bufke** [comment] 2015-02-11 19:44
Dang - any error messages? I can't reproduce.
![screenshot from 2015-02-11 14 19 54](https://cloud.githubusercontent.com/assets/739307/6154352/1cf60d58-b1f9-11e4-8476-b68dee90ed0f.png)

**Comment by orlovegor** [comment] 2015-02-12 11:02
There were error messages in debug console but that was due that I was impersonated as another user in my application. When I login as myself everything works as expected, thanks!

**Comment by lspitaels** [comment] 2015-02-16 08:19
I've just updated and it works great.
Thank you very much.
