### ISSUE TITLE
Group by support is broken

### ISSUE THREAD

**Issue by destroyers34** [burke-software/django-report-builder#20] opened 2013-02-28 20:25 UTC
What is the group checkbox in display fields tab ? At first i was thinking about a group by option but every time I tried using it I get a Field Errors.

**Comment by amlozano1** [comment] 2015-04-10 23:42
Anybody @curtisstpierre still working on this? I want to use django-report-builder but group by a user foreign key is kind of critical.

**Comment by curtisstpierre** [comment] 2015-04-11 00:14
Is it still an issue?

**Comment by amlozano1** [comment] 2015-04-11 00:19
Yeah as far as I can tell, the issue is open still and there hasn't been a pull.
I just found this project and installed it, trying to group by a foreign key results in a bunch of blank fields.

**Comment by curtisstpierre** [comment] 2015-04-11 00:21
Yeah that's still broken, alright I know the solution, I just haven't got around to building a test case for it.

**Comment by amlozano1** [comment] 2015-04-11 01:14
If you have the solution you should post it without the test case and maybe we can open a separate issue to write the test case?

**Comment by curtisstpierre** [comment] 2015-04-13 03:56
I need to reimplement my change in the new version of the code, I'll attempt to get something done this week

**Comment by bufke** [comment] 2015-04-14 21:27
Would love to see any progress even if it's a work in progress. I'm considering refactoring the report_to_list function as it's pretty confusing as is.

**Comment by grantjenks** [comment] 2015-06-25 17:08
This is fixed in #160 and django-report-utils#15

**Closed by grantjenks** 2015-06-25 17:08 UTC
