### ISSUE TITLE
AttributeError in admin after reporting is used

### ISSUE THREAD

**Issue by wilburb** [burke-software/django-report-builder#218] opened 2016-01-15 18:22 UTC
I am not sure on exact steps to reproduce yet, as this was reported to me from a user, but I'll give the general idea.

The user created a report, and then later attempted to load the django admin page that uses the same model as used in the report. After doing this the admin page gave an AttributeError.

AttributeError: ‘ReportObjectHere’ object has no attribute ‘related_m2m_inline_through_field_here’

Restarting the web server resolves this issue, but we have now seen it twice. It is as though django loses the related field after reporting. To clarify, the m2m field is on another model with the model being reported from as its m2m.

Does this give enough information to either suggest there is indeed a bug, and or shed light on something I am doing incorrectly?

Thanks.

**Comment by grantjenks** [comment] 2016-01-19 19:47
Are you using Django 1.7 or 1.8?

**Comment by wilburb** [comment] 2016-01-19 20:02
1.8





On Tue, Jan 19, 2016 at 11:47 AM -0800, "Grant Jenks" <notifications@github.com> wrote:












Are you using Django 1.7 or 1.8?

**Comment by grantjenks** [comment] 2016-01-19 23:42
Could you try with Django 1.7? I haven't seen this issue before and I'm still on 1.7. A lot of internals were changed with 1.8 and I think this may be one of the corner cases.

Without repro steps, I know it's hard to answer that question. But I wanted to capture these notes in the report.

**Comment by wilburb** [comment] 2016-01-20 04:04
I attempted to revert to 1.7, but I'm afraid I don't know what needs to be done to get my database back to 1.7. 

I was able to get reproduce steps though. I also attempted to make a bare bones project, but the report_builder/ urls hang due to an angular issue, and I'm not familiar enough with angular (ie, at all) to know how to troubleshoot why they were hanging. Here is what I believe to be relevant info.

    # models.py
    class Person( AbstractBaseUser, PermissionsMixin ):
        ...

    # not to be confused with django groups, I shouldn't have named it Group
    class Group( models.Model ):
        name = models.CharField( max_length=250 )
        leaders = models.ManyToManyField( settings.AUTH_USER_MODEL, blank=True, related_name='groups_managed', through='GroupLeadership' )
        ...

    class GroupLeadership( models.Model ):
        group = models.ForeignKey( Group )
        member = models.ForeignKey( Person )
        ...

    # admin.py
    class LeadersInline( admin.TabularInline ):
        model = Group.leaders.through
        ...

    class PersonAdmin( admin.ModelAdmin ):
        model = Person
        inlines = [LeadersInline, ...]
        ...

To Reproduce:

1. Bring up a detail view for a Person record
1. It works and loads entirely, inlines intact.
1. Open a page for a report with a base model of Group. This can be as simple as refreshing an existing report. ie. http://localhost:5757/report_builder/report/3
1. Attempt to reload the person record from the first step. FieldDoesNotExist at /admin/tour/person/1/
No related field named 'groupleadership'
1. restart, rinse, lather, repeat

As I mentioned above, I have a pretty basic project with Book and Author models to repeat this, but Angular has an issue when visiting the report_builder. I will continue attempting to get the example working so that I can hopefully provide you with failure code. Unfortunately I probably cannot share much more of the real project code.

Thanks for your help and for sharing your project!

**Comment by gkirkpatrick** [comment] 2016-03-03 14:25
I have also been getting this error a lot on the django admin. I wasn't sure it was related to report builder until just recently. 

Are you running your project on a production stack? Nginx/uwsgi? Or does the problem happen on the dev server? I have only seen the issue on my production environment but I haven't spent much time trying to reproduce it on my dev server.

**Comment by nicosenzil** [comment] 2016-04-06 19:45
I found in the file model_introspection.py (report_utils package) this method:

def get_relation_fields_from_model(model_class):
    """ Get related fields (m2m, FK, and reverse FK) """
    relation_fields = []
    all_fields_names = model_class._meta.get_all_field_names()
    for field_name in all_fields_names:
        field = model_class._meta.get_field_by_name(field_name)
        # get_all_field_names will return the same field
        # both with and without _id. Ignore the duplicate.
        if field_name[-3:] == '_id' and field_name[:-3] in all_fields_names:
            continue
        if field[3] or not field[2] or hasattr(field[0], 'related'):
            field[0].field_name = field_name
            relation_fields += [field[0]]
    return relation_fields

I think the line field[0].field_name = field_name is the problem when you change the attribute field_name.

I've replaced the attribute field_name to field_name_report in that file and in the report_builder package. Also, I've changed the RelatedFieldsView class in the report_builder api in the method post:

            try:
                field_name = new_field.field_name
            except:
                field_name = new_field.field_name_related

            result += [{
                'field_name': field_name,
                'verbose_name': verbose_name,
                'path': path,
                'help_text': getattr(new_field, 'help_text', ''),
                'model_id': model_ct.id,
                'parent_model_name': model_name,
                'parent_model_app_label': app_label,
                'included_model': included_model,
            }]
        return Response(result)


I don't thing it's the better solution but it's working now.

**Comment by nicosenzil** [comment] 2016-04-06 22:31
Finally I added the following lines to the get_relation_fields_from_model method

 if not isinstance(field[0], models.ForeignKey):
            continue

Now is working fine but obviously doesn't show the inverse relations.

```
def get_relation_fields_from_model(model_class):
    """ Get related fields (m2m, FK, and reverse FK) """
    relation_fields = []

    all_fields_names = model_class._meta.get_all_field_names()
    for field_name in all_fields_names:
        field = model_class._meta.get_field_by_name(field_name)
        if not isinstance(field[0], models.ForeignKey):
            continue
        # get_all_field_names will return the same field
        # both with and without _id. Ignore the duplicate.
        if field_name[-3:] == '_id' and field_name[:-3] in all_fields_names:
            continue
        if field[3] or not field[2] or hasattr(field[0], 'related'):
            field[0].field_name = field_name
            relation_fields += [field[0]]
    return relation_fields
```

**Comment by vitorfragoso** [comment] 2016-06-22 02:15
I have the same issue using Django 1.9.7 and Python3.4.3. As soon as I restart the server, it works again.

**Comment by smwise** [comment] 2016-07-18 17:14
The problem is related to setting field_name, but it's specifically setting field names on objects that aren't regular fields but relations. To take ForeignKey as an example, say we have two models, Book and Author, and Book has a ForeignKey "author" to Author. Book has "author" as one of its fields, and setting field_name on that is fine. Author has "book_set" that points back to Book, and that in turn is a ManyToOneRel when gotten via get_field_by_name. Setting the field_name on that, which was already set by Django and is the pk or the to_field value, is what causes the exception in the admin. If you check Book.author.field.rel.field_name after setting field_name, that is what just changed to "book" but should be (by default) "id".
Django uses this field_name in ManyToOneRel's get_related_field, and "book" instead of "id" can be found as a field but isn't concrete.

As far as report builder is concerned, the method that sets field_name seems to only be used in get_related_fields in a Mixin that is used in RelatedFieldsView, under api views. All that in turn uses field for is to get some attributes from it. Some workarounds, some of which were already suggested, would be to use a different attribute for the field's name that isn't also used by Django, use copies of the fields, or return the attributes from the fields in a dict instead of the fields themselves.

Regarding Django, the get_related_fields pieces exist in 1.7, so I don't know why it would have worked then, but get_all_field_names seems to be changing so perhaps something important changed as far as getting the fields themselves. I'm using Django 1.8 and Python 2.7.6.

**Comment by gkirkpatrick** [comment] 2016-09-20 15:26
Btw, not sure if this issue should be closed it looks like it was addressed in pull request #237 

 In my short testing so far updating to the latest report builder and report builder utils seems to have solved this.

**Comment by smwise** [comment] 2016-09-23 19:23
I had been using a fork of django-report-builder and just switched back - 3.4.3 no longer breaks the admin for me!

One thing - I didn't intend to sneak this by but my pull request to address this also removed references to django-report-utils from django-report builder. But, django-report-utils is still included in setup.py. It should probably be removed?

**Comment by bufke** [comment] 2016-09-24 16:43
Oh - I just removed it now from setup.py. I'll close this issue, reopen if it's not fixed.

**Closed by bufke** 2016-09-24 16:43 UTC
