### ISSUE TITLE
django.db.backends.util in execute ProgrammingError: relation "report_builder_report_starred" does not exist

### ISSUE THREAD

**Issue by bkvirendra** [burke-software/django-report-builder#127] opened 2015-01-19 20:40 UTC
I had Django report builder installed for one of my apps, and for some reason the Report builder does not support Custom user profile. Hence I could not complete the migrations for report builder.

Then I decided to remove report-builder, by using this tutorial, http://mherman.org/blog/2013/07/04/removing-a-django-app/#.VL1qvy6Ufxg
(it makes use of South for removing the app)

It deleted all the tables for django-report-builder, and then I removed the app from 'INSTALLED_APPS' from settings.

Now I'm trying to delete a User from the admin panel, but I'm unable to delete it because there exists some relationship from the User to the report_builder.

The following error is what I get:

```
2015-01-19T20:22:21.988630+00:00 app[web.1]: ERROR 2015-01-19 20:22:21,982 base 9 140121359582976 Internal Server Error: /admin/accounts/user/566/delete/
2015-01-19T20:22:21.988632+00:00 app[web.1]: Traceback (most recent call last):
2015-01-19T20:22:21.988633+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
2015-01-19T20:22:21.988635+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2015-01-19T20:22:21.988636+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 432, in wrapper
2015-01-19T20:22:21.988638+00:00 app[web.1]:     return self.admin_site.admin_view(view)(*args, **kwargs)
2015-01-19T20:22:21.988639+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
2015-01-19T20:22:21.988640+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2015-01-19T20:22:21.988642+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
2015-01-19T20:22:21.988643+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2015-01-19T20:22:21.988645+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
2015-01-19T20:22:21.988646+00:00 app[web.1]:     return view(request, *args, **kwargs)
2015-01-19T20:22:21.988648+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
2015-01-19T20:22:21.988650+00:00 app[web.1]:     return bound_func(*args, **kwargs)
2015-01-19T20:22:21.988652+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
2015-01-19T20:22:21.988653+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2015-01-19T20:22:21.988654+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
2015-01-19T20:22:21.988665+00:00 app[web.1]:     return func(self, *args2, **kwargs2)
2015-01-19T20:22:21.988667+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
2015-01-19T20:22:21.988668+00:00 app[web.1]:     return func(*args, **kwargs)
2015-01-19T20:22:21.988670+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1457, in delete_view
2015-01-19T20:22:21.988671+00:00 app[web.1]:     [obj], opts, request.user, self.admin_site, using)
2015-01-19T20:22:21.988673+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/util.py", line 109, in get_deleted_objects
2015-01-19T20:22:21.988674+00:00 app[web.1]:     collector.collect(objs)
2015-01-19T20:22:21.988676+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/util.py", line 160, in collect
2015-01-19T20:22:21.988677+00:00 app[web.1]:     return super(NestedObjects, self).collect(objs, source_attr=source_attr, **kwargs)
2015-01-19T20:22:21.988679+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/deletion.py", line 196, in collect
2015-01-19T20:22:21.988680+00:00 app[web.1]:     elif sub_objs:
2015-01-19T20:22:21.988681+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 100, in __nonzero__
2015-01-19T20:22:21.988683+00:00 app[web.1]:     self._fetch_all()
2015-01-19T20:22:21.988684+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
2015-01-19T20:22:21.988686+00:00 app[web.1]:     self._result_cache = lis
t(self.iterator())
2015-01-19T20:22:21.988687+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
2015-01-19T20:22:21.988688+00:00 app[web.1]:     for row in compiler.results_iter():
2015-01-19T20:22:21.988690+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
2015-01-19T20:22:21.988691+00:00 app[web.1]:     for rows in self.execute_sql(MULTI):
2015-01-19T20:22:21.988693+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
2015-01-19T20:22:21.988694+00:00 app[web.1]:     cursor.execute(sql, params)
2015-01-19T20:22:21.988703+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
2015-01-19T20:22:21.988705+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2015-01-19T20:22:21.988706+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
2015-01-19T20:22:21.988708+00:00 app[web.1]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
2015-01-19T20:22:21.988709+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
2015-01-19T20:22:21.988710+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2015-01-19T20:22:21.988712+00:00 app[web.1]: ProgrammingError: relation "report_builder_report_starred" does not exist
2015-01-19T20:22:21.988713+00:00 app[web.1]: LINE 1: ...nts_user"."share_activities_with_nonfriends" FROM "report_bu...
```

**Comment by somghosh** [comment] 2015-01-26 11:47
+1

**Comment by bufke** [comment] 2015-01-26 20:52
@somghosh @bkvirendra could you provide more information. I can't reproduce this.

What version of django?
What version of report builder?

**Comment by bufke** [comment] 2015-02-04 23:24
Closing till I get more information on the issue. Feel free to reopen.

**Closed by bufke** 2015-02-04 23:24 UTC
