### ISSUE TITLE
Reverse for 'report_download_xlsx' with arguments '(1,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []

### ISSUE THREAD

**Issue by davemerwin** [burke-software/django-report-builder#201] opened 2015-08-20 21:45 UTC
Not sure what is causing this. We'll, I can read the error, but I can't see what is happening. This is a fresh install. DRF is already installed. Any ideas?

**Comment by bufke** [comment] 2015-08-22 16:59
Did you add the urls.py line? http://django-report-builder.readthedocs.org/en/latest/quickstart/

**Comment by davemerwin** [comment] 2015-08-24 19:35
I did. Everything works until that point.

On Sat, Aug 22, 2015 at 9:59 AM, David Burke <notifications@github.com>
wrote:

> Did you add the urls.py line?
> http://django-report-builder.readthedocs.org/en/latest/quickstart/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/burke-software/django-report-builder/issues/201#issuecomment-133727136>
> .
>



-- 
Dave Merwin

Schedule a time with me: http://calendly.com/davemerwin

http://facebook.com/davemerwin
http://twitter.com/davemerwin
http://www.davemerwin.com
My Profile: http://www.linkedin.com/in/merwin
541.335.1832

**Comment by grantjenks** [comment] 2015-08-31 20:20
Dupe of #203

**Closed by grantjenks** 2015-08-31 20:20 UTC
