### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by tluanga** [burke-software/django-report-builder#294] opened 2018-08-06 06:57 UTC
dev-OG_Ndht5\lib\site-packages\report_builder\models.py", line 460
    def run_report(self, file_type, user=None, queryset=None, async=False, scheduled=False, email_to:str = None):
                                                                  ^
SyntaxError: invalid syntax

**Comment by bufke** [comment] 2018-08-06 13:58
I suspect this is a duplicate of https://gitlab.com/burke-software/django-report-builder/issues/278

Reopen if you think otherwise.

**Closed by bufke** 2018-08-06 13:58 UTC
